  var viewer = new PhotoViewer();
  viewer.enableAutoPlay();
  viewer.enableLoop();
  viewer.setSlideDuration(3000);
  viewer.setBackgroundColor('#FFFFFF');
  viewer.setShadeColor('#C32148');
  viewer.setFontSize(16);
  viewer.add('image/gallery/ss1.jpg', 'Entrance to ACC lobo', '2014', 'ACC Lobo');
  viewer.add('image/gallery/ss2.jpg', 'Kennel No.1 (and Reception) built in 1992', '2014', 'ACC Lobo');
  viewer.add('image/gallery/ss3.jpg', 'Kennel No.2 built in 2007', '2014', 'ACC Lobo');
  viewer.add('image/gallery/ss4.jpg', 'The Dieleman family', '2008', 'ACC Lobo');
  viewer.add('image/gallery/ss5.jpg', 'A warm welcome awaits you!', '2014', 'ACC Lobo');  
  viewer.add('image/gallery/ss6.jpg', 'Our spacious reception', '2014', 'ACC Lobo');
  viewer.add('image/gallery/ss7.jpg', 'Indoor kennels', '2014', 'ACC Lobo');
  viewer.add('image/gallery/ss8.jpg', 'Our guests are given lots of exercise', '2014', 'ACC Lobo');
  viewer.add('image/gallery/ss9.jpg', 'Our outdoor paddocks', '2013', 'ACC Lobo');
  viewer.add('image/gallery/ss10.jpg', 'Martin Dieleman helps at playtime', '2014', 'ACC Lobo');
  viewer.add('image/gallery/ss11.jpg', 'A vast enclosed play area', '2014', 'ACC Lobo');  
  viewer.add('image/gallery/ss12.jpg', 'Cute puppies await adoption', '2014', 'ACC Lobo'); 
  viewer.add('image/gallery/ss13.jpg', 'Grooming is a speciality at ACC Lobo', '2014', 'ACC Lobo');
  viewer.add('image/gallery/ss14.jpg', 'Gertie Dleleman makes a friend!', '2014', 'ACC Lobo');
  viewer.add('image/gallery/ss15.jpg', 'Cats enjoy the catroom', '2014', 'ACC Lobo');  
  viewer.add('image/gallery/ss16.jpg', 'Our sun canopy to keep it cool', '2014', 'ACC Lobo');   
  viewer.add('image/gallery/ss17.jpg', 'Another way of cooling down!', '2014', 'ACC Lobo');   
  viewer.add('image/gallery/ss18.jpg', 'A different sort of guest', '2007', 'ACC Lobo');  
  viewer.add('image/gallery/ss20.jpg', 'Come visit us anytime!', '2014', 'ACC Lobo');